### ISSUE TITLE
Add `@textpattern/owners` to direct access collaborators

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-zero-theme#1]
I can't add @textpattern/owners to direct access collaborators, assuming it's cos I'm not in that group.

@Bloke or @philwareham - when either of you have a moment, please add @textpattern/owners to direct access collaborators ('admin' tier). Thank you.

**Comment by Bloke** [comment]
Well I clicked _Add team_ chose textpattern/owners and set them as Admin but it's not showing anything different 🤷‍♂️

**Comment by petecooper** [comment]
Same here, @Bloke - thanks for trying!

**Comment by bloatware** [comment]
I've been given access to the repo, though I'm not textpattern owner..

**Comment by petecooper** [comment]
@bloatware You're part of @textpattern/cms-team
